CREATE ROLE dbt_test_user_1;
CREATE ROLE dbt_test_user_2;
CREATE ROLE dbt_test_user_3;

CREATE ROLE root WITH PASSWORD 'password';
ALTER ROLE root WITH LOGIN;
GRANT CREATE, CONNECT ON DATABASE dbt TO root WITH GRANT OPTION;
CREATE DATABASE "dbtMixedCase";
GRANT CREATE, CONNECT ON DATABASE "dbtMixedCase" TO root WITH GRANT OPTION;