// DO NOT EDIT!!!
// This file is generated by ./scripts/gen_cdn_driver_checksums.sh

#[allow(clippy::type_complexity)]
#[rustfmt::skip]
pub static SORTED_CDN_DRIVER_CHECKSUMS: [(
    (
        &str, // backend
        &str, // target_os
        &str, // arch
        &str, // version
    ),
    &str, // checksum
); 54] = [
    (
        ("bigquery", "apple-darwin", "aarch64", "0.18.0+dbt0.0.10"),
        "2fd7deeb5e71f322a6d71e0b28070493c0efb6766436b49d65669d59e96c42cb",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.18.0+dbt0.0.8"),
        "9c7d6743137cca62b14b9fb2e1d8c48689806d6199f299080ecbc8d63c8582fc",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.18.0+dbt0.0.9"),
        "74d1a69a9ca716a1d70d83a5d7ae11722e067618bfe2eb81be63815ed7943873",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.18.0+dbt0.0.10"),
        "0d982115f3a225e08d88d4033e7d706235f60198cb423e4080b48e114200a4ce",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.18.0+dbt0.0.8"),
        "b19979c0a2d92735591e2fdf03f4281c8f5a39bca75fa5e239e45d7e0945b3d2",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.18.0+dbt0.0.9"),
        "55c3dae82e0aed924782a69b18b0ced44c2d74d193d9a9234a99ff97c5e82bc2",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.10"),
        "dd602bb2d14adbf932b0f0c4ff0cd62f7cacdbcbab6575aa1e278308877e3c65",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.8"),
        "ae25918830efe1b9abf3710245faa40839f243523a17ea3faaf0fc7392661b1e",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.9"),
        "f709915d8285b7c7ed0df7e3008a1ecd67a92cf421f9909ccae5c4297a5b809c",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.10"),
        "df7087bd9e57024738587e314e408bb6d2e524ff4231f6d4eabbc41a08028a4b",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.8"),
        "cd3d7f8ab15b0d02c739a2b479c07be5e84893fdf3b14af5162804aed29c3f78",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.9"),
        "eebe063c97f81f6a95938b303869c337a1d3a1a19f8d7076d1396ee44afda1b6",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.10"),
        "a7dba3d86e81f7adefdb526f490744967370e347f4672b1fb7ee3b38c4323ddb",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.8"),
        "658dc88f2cde4bb042a5f8dc5d36d6b15c79995649092106e0a7a9f8e4be841a",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.9"),
        "da668075370e7214b6cc0e4b2dfa1aea8c7d64cfed5166197b95514f49160138",
    ),
    (
        ("databricks", "apple-darwin", "aarch64", "0.18.0+dbt0.0.4"),
        "3e21c4c8f547c99bc97751b46654cffa0a2be4d2522af8428ea02ea4b1ed6146",
    ),
    (
        ("databricks", "apple-darwin", "aarch64", "0.18.0+dbt0.0.5"),
        "76aa60a979bb141dff6af4ecdf6881b7c341d02364552d2274e954add5f52cb8",
    ),
    (
        ("databricks", "apple-darwin", "aarch64", "0.18.0+dbt0.0.6"),
        "747891eaeef3d058a2829aafc3b69ef3f4d07f9998ebe56b3add4d5041b7c6e9",
    ),
    (
        ("databricks", "apple-darwin", "x86_64", "0.18.0+dbt0.0.4"),
        "bcb45c92249b6fc57a7dc98259f2d5d18016466e820f1a423212bc919316cc5b",
    ),
    (
        ("databricks", "apple-darwin", "x86_64", "0.18.0+dbt0.0.5"),
        "2c420960835c8ed7e792937f01022213ca07a975e2c1a0a5b0ad7ad7f8e37851",
    ),
    (
        ("databricks", "apple-darwin", "x86_64", "0.18.0+dbt0.0.6"),
        "ff2dedef48b7fade19c403635354436c39c352ae8549fbfa7cdc3953ff86bcdd",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.4"),
        "cc1e2112a2571c77924602829963055d1b7ae64df16bd827a177bc7ecb6cbe55",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.5"),
        "83fdc2dc6dd1f821a6a1975ff27fd73cd0b8a43d15ab2a43f874d044e7590dd9",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.6"),
        "158a093844214dab63bf4ac3e1eb3ceba6956a7bb87265ff6874d4f26d11f023",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.4"),
        "7fdd7616dfbbc114e0f57fa3c7abe5a2d312562678e295bdc44a5c308c7952ed",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.5"),
        "bb9a5773f5ae12f2bf46e113dc9f559e182b0833fe0e9174356ed8145e529996",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.6"),
        "a2ad1eda57b708ead1843dd1e07dea10639f90e478dad058dbe1dd11eea0265b",
    ),
    (
        ("databricks", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.4"),
        "934e8eef44da53431bb7bd7539a0049de83f5254e5db9567ceee327c4acb01c0",
    ),
    (
        ("databricks", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.5"),
        "2e55c582a0de81b17f2d5fbd3ddf373e2c404b51c4a7ef6bf9c522b0591c4f66",
    ),
    (
        ("databricks", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.6"),
        "ed516f0aedde04c97f079628a18ca3c1a683c18c3ffc218a5faca511c2e27c05",
    ),
    (
        ("postgresql", "apple-darwin", "aarch64", "0.17.0+dbt0.0.1"),
        "6f1e25c0a4da44697bb449091ebd14575a92bd27e48cce49fdd56d0a7ad5066a",
    ),
    (
        ("postgresql", "apple-darwin", "aarch64", "0.18.0+dbt0.0.2"),
        "fb3a52e89163a61e09f5d85d03cd8d7afaaae697617e2b981128f375faa53aeb",
    ),
    (
        ("postgresql", "apple-darwin", "x86_64", "0.17.0+dbt0.0.1"),
        "40f6627b9ecabc659c9750c06a8d836b86e807044bea150e74ac4550ac641cbf",
    ),
    (
        ("postgresql", "apple-darwin", "x86_64", "0.18.0+dbt0.0.2"),
        "da4087189a70deba7040d7f00faea221b492d00855d9d8eff56787eb5fbf02c1",
    ),
    (
        ("postgresql", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.2"),
        "0f3989966d5308b172d5b4cdb8d4cde6752c10ae175a1200f738a0f73c45edde",
    ),
    (
        ("postgresql", "manylinux_2_17-linux-gnu", "x86_64", "0.17.0+dbt0.0.1"),
        "ddeaafefdd79dfddc38c48a405b6789e6f51985b32be163a322eaadb55d9ca30",
    ),
    (
        ("postgresql", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.2"),
        "a14e9532dc54371698c9730d7904f03431137c2c216b22ac623e84552b7cc93e",
    ),
    (
        ("postgresql", "pc-windows-msvc", "x86_64", "0.17.0+dbt0.0.1"),
        "cff84d5f3db4fe0efbfc64591d4005d81020261faee24c4b9b7b7211c4895fbd",
    ),
    (
        ("postgresql", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.2"),
        "b5ee9393977dff39f62d4196938a90313bea3681b1183ddb1e2f8afb92af23c8",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.18.0+dbt0.0.10"),
        "0ce8a9de9ce44e3066a40b8a19b03db06e5967c6aa24057693f8954ab89250f7",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.18.0+dbt0.0.7"),
        "37514e28d36d9626770a42e1c77fdd433ed852ad4e29b744987b91ce744b16a6",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.18.0+dbt0.0.8"),
        "7a1a16e8b8b32b6d53dfb1590b75340d3d71af511c68798033b5230f180aefcf",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.18.0+dbt0.0.10"),
        "494a7f5d3e12db02bcbc33ab6a28f00ee912d63cf60d7db940a8040aec078189",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.18.0+dbt0.0.7"),
        "865d248ec084937f3236ce3b7183cc85e49344cd9929e34bc0302f0dca8a67cb",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.18.0+dbt0.0.8"),
        "f32b3364c84111bca05e1161e9c7a2ceade81aa81dc0af37b57450383dd3217d",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.10"),
        "7fea332ea4a951bcc9dcffc99d8307c2592832781b98492fb7ec2ecedb57a5ae",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.7"),
        "1f2d4bacee219ea68b21cf32e15179271f43ee51090bf133ee5c4d67d6645286",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.8"),
        "48aaca010d0ae6c83bae39e109d9d0d91845352eb8073cc47708e38fb3bbea26",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.10"),
        "c2b4a32eefb112ed0af9b9704f2377cb538b25b5cd90539282987f556941b533",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.7"),
        "73310197405920e50f563a099123f7626f3e446d37cf57465701d3de682ec32b",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.8"),
        "051f4f2bad15940aaa1165316cf76a2c32bf09a48eff1d537560f469188370d8",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.10"),
        "e5f65f57625647a1da7f9cd46523c3076c557f6c77e7afadf9f92a20c1600aac",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.7"),
        "aebfbeab35aeeb91f51e4c1baa166d094b23ea2161c405da1b44ebe18a236af1",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.8"),
        "3600c6c80733bf0de5f6295e2f717c72c2bdb311013309b2152fd8310cfac32b",
    ),
];
